language: ruby
cache: bundler
rvm:
    - 2.1.5
sudo: false
addons:
    apt:
        packages:
            - vim-gtk

script: bundle exec rake ci
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
